name: CI/CD Pipeline

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main, dev]

env:
  SRC_PROJECT_FOLDER: "."
  SRC_PYTHON_VERSION: "3.11"

jobs:
  setup-lint:
    name: Setup and Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Python & Install Dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{ env.SRC_PYTHON_VERSION }}
          uv-group: "pipeline"
          uv-extra: "--all-extras"

      - name: Lint Code
        uses: ./.github/actions/lint-code
        with:
          src-project-folder: ${{ env.SRC_PROJECT_FOLDER }}

  build-deploy-mkdocs:
    if: github.ref == 'refs/heads/main'
    name: Build MkDocs Documentation
    runs-on: ubuntu-latest
    needs: setup-lint

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Python & Install Dependencies
        uses: ./.github/actions/setup-python-env
        with:
          src-python-version: ${{ env.SRC_PYTHON_VERSION }}
          uv-group: "documentation"

      - name: Get Version
        id: version
        uses: ./.github/actions/obtain-version

      - name: Build MkDocs Site with Mike
        uses: ./.github/actions/build-mkdocs
        with:
          docs-version: ${{ steps.version.outputs.version }}
